### PR TITLE
Different key modifier solutions for PyQt5 and PyQt6

### PR DESCRIPTION
**Pull request by willend**
Fixes the issue with mcplot-pyqtgraph mentioned also in https://github.com/McStasMcXtrace/McCode/pull/1652

### CODE REVIEW

**Comment by farhi** [comment]
Thanks for this, this is the right file, as seen from the history there were a few edits, and your solution seems to cover the Qt versions as needed:
- https://github.com/McStasMcXtrace/McCode/commits/main/tools/Python/mccodelib/pqtgfrontend.py

This is an evolution to #1582

**Comment by willend** [comment]
Merging

**Comment by willend** [comment]
Hmm. This was apparently a partial fix only, Qt version correctly detected on Linux but not macOS and Windows.... Looks like I will use a different if(): else: clause

**Comment by willend** [comment]
https://github.com/McStasMcXtrace/McCode/pull/1656 seems to be a full solution

**Pull request merged**
