### PR TITLE
Doc: add man pages

### PR DESCRIPTION
**Pull request by farhi**
I have generated Markdown pages for every tool we have.
The MD are obtained from the raw --help and formatted "by hand". Automatic tools do not perform so nicely.

Once X-ray MD files are there, they are copied for the McStas part, with many find/replace (e.g. McXtrace/McStas, MX/MC, mx/mc, X-ray/Neutron, photon/neutron...).

Then the man pages are generated with:
```
for i in *.md; do bn=$(basename -s .md $i); pandoc --standalone --to man $i -o ${bn}.1; done
```
We shall see if we need to distribute the MD/man pages in each tool, or keep them gathered here (in which case links to them could be set in the target tool directories).

### CODE REVIEW

**Comment by farhi** [comment]
And all is now passing ;-)
 We have nice man pages, configured and stored together with manuals... This allows to create the real man pages afterwards.

**Comment by willend** [comment]
@farhi cool, I will now merge.

Next on my list is testing how the "oldschool" Deb packages (via `buildscripts/`) behave.

**Comment by farhi** [comment]
I think the buildscripts DEBs behave OK, as they now build with LEGACY=OFF.
The only issue I see is that the version number is built in the package names, and the package version given to cpack is always 1.0.
This brings incompatibilities when upgrading a mcxtrace/mcstas installation (a file in the system belongs to 2 packages).
One way to solve is to forward the version number properly to cpack, and remove it from the deb names.

**Comment by willend** [comment]
Hi E,

To really behave "legacy" I think they will have to be built with LEGACY=ON, but again this is of course only a temporary thing to consider as we will be recommending / using the salsa-provided approach going forward.

I will try building a local set using LEGACY=ON for comparison with what I am currently testing - which uses LEGACY=OFF. In this setup I see a couple of immediate issues:
* The value of $MCCODE is wrong inside the "environment" (mcstas-3.4.55-environment gives $MCSTAS=/usr/share/mcstas/share/mcstas/resources, but I am sure this is just a matter of using the CMAKE vars correctly in the env script)
* The node / npm packages for the "fully up-to-date" mcdisplay-webgl are not installed - perhaps these should rather be injected in the user .mccode/version/ folder on first launch of the tool...)

If you have time we should perhaps have a zoom soonish?

**Comment by willend** [comment]
What I am in other words thinking is:

The buildscripts/*deb* scripts should behave like historically and should NOT try to adhere to the Debian policies - the "proper" packages from salsa will provide that.

I have a fix for the env script in the pipe (should work with both LEGACY on and off and will come as a PR)

**Comment by farhi** [comment]
I agree that the buildscripts/deb scripts should not reproduce the pure Debian builds. However, the bugs reported on the pure Debian side should be preferably solved, when applicable, into our upstream, otherwise we have plenty of patches on the pure Debian side.

I just ran then pure Debian package build on our github McCode tree. Not using the buildscripts.
- copy `debian` directory from https://salsa.debian.org/science-team/mccode 
- `sudo apt install devscripts dh-cmake recode python3-all dh-python`
- `debuild -b`

The output of the final lintian checks is shown below.
The items to take care of:
- The `no-manual-page` will be solved when adding a `pandoc` call from the /usr/share/mcxtrace/dpc/manuals/*.md -> .1 and store them in `/usr/share/man/man1`. Can be done on the pure Debian side (not relevant for conda).
- `mcdisplay-matplotlib` seems to be tagged as python2
- `mcxtrace/comps/data/get_xray_db_data` interpreter is /usr/bin/bash, should be /bin/bash. Will fix.
- the newly generated `.md` files seem to be flagged as executable.
- the matlab scripts are flagged as executable. 
- the `unusual-interpreter python` warnings assume python -> python3.
- script-not-executable *.desktop -> remove the shebang at start (must not be executed).

I will look into this, and pass through a PR for that what can be easily solved.

```
E: mcstas-mcdisplay-matplotlib: python2-script-but-no-python2-dep /usr/bin/python2 (does not satisfy python2:any | python2-minimal:any) [usr/share/mcstas/tools/Python/mcdisplay/matplotlib/mcdisplay.py]
E: mcxtrace-mxdisplay-matplotlib: python2-script-but-no-python2-dep /usr/bin/python2 (does not satisfy python2:any | python2-minimal:any) [usr/share/mcxtrace/tools/Python/mxdisplay/matplotlib/mxdisplay.py]
E: mcxtrace-comps: wrong-path-for-interpreter /usr/bin/bash != /bin/bash [usr/share/mcxtrace/resources/data/get_xray_db_data]
W: mcstas: executable-not-elf-or-script [usr/share/mcstas/resources/doc/manuals/mcstas.md]
W: mcstas-mcdisplay-matlab: executable-not-elf-or-script [usr/share/mcstas/resources/doc/manuals/matlab/mcdisplay/mcdisplay-matlab.md]
W: mcstas-mcdisplay-matlab: executable-not-elf-or-script [usr/share/mcstas/tools/matlab/mcdisplay/mcdisplay.m]
W: mcstas-mcdisplay-matplotlib: executable-not-elf-or-script [usr/share/mcstas/resources/doc/manuals/Python/mcdisplay/matplotlib/mcdisplay-matplotlib.md]
W: mcstas-mcdisplay-pyqtgraph: executable-not-elf-or-script [usr/share/mcstas/resources/doc/manuals/Python/mcdisplay/pyqtgraph/mcdisplay-pyqtgraph.md]
W: mcstas-mcdisplay-pyqtgraph: executable-not-elf-or-script [usr/share/mcstas/tools/Python/mcdisplay/pyqtgraph/mcdisplay-pyqtgraph.md]
W: mcstas-mcdisplay-webgl-classic: executable-not-elf-or-script [usr/share/mcstas/resources/doc/manuals/Python/mcdisplay/webgl-classic/mcdisplay-webgl-classic.md]
W: mcstas-mcdoc: executable-not-elf-or-script [usr/share/mcstas/resources/doc/manuals/Python/mcdoc/mcdoc.md]
W: mcstas-mcgui: executable-not-elf-or-script [usr/share/mcstas/resources/doc/manuals/Python/mcgui/mcgui.md]
W: mcstas-mcplot-matlab: executable-not-elf-or-script [usr/share/mcstas/resources/doc/manuals/matlab/mcplot/mcplot-matlab.md]
W: mcstas-mcplot-matlab: executable-not-elf-or-script [usr/share/mcstas/tools/matlab/mcplot/mcplot.m]
W: mcstas-mcplot-matplotlib: executable-not-elf-or-script [usr/share/mcstas/resources/doc/manuals/Python/mcplot/matplotlib/mcplot-matplotlib.md]
W: mcstas-mcplot-pyqtgraph: executable-not-elf-or-script [usr/share/mcstas/resources/doc/manuals/Python/mcplot/pyqtgraph/mcplot-pyqtgraph.md]
W: mcstas-mcplot-svg: executable-not-elf-or-script [usr/share/mcstas/resources/doc/manuals/Python/mcplot/svg/mcplot-svg.md]
W: mcstas-mcrun: executable-not-elf-or-script [usr/share/mcstas/resources/doc/manuals/Python/mcrun/mcrun.md]
W: mcxtrace: executable-not-elf-or-script [usr/share/mcxtrace/resources/doc/manuals/mcxtrace.md]
W: mcxtrace-mxdisplay-matlab: executable-not-elf-or-script [usr/share/mcxtrace/resources/doc/manuals/matlab/mxdisplay/mxdisplay-matlab.md]
W: mcxtrace-mxdisplay-matlab: executable-not-elf-or-script [usr/share/mcxtrace/tools/matlab/mxdisplay/mcdisplay.m]
W: mcxtrace-mxdisplay-matplotlib: executable-not-elf-or-script [usr/share/mcxtrace/resources/doc/manuals/Python/mxdisplay/matplotlib/mxdisplay-matplotlib.md]
W: mcxtrace-mxdisplay-pyqtgraph: executable-not-elf-or-script [usr/share/mcxtrace/resources/doc/manuals/Python/mxdisplay/pyqtgraph/mxdisplay-pyqtgraph.md]
W: mcxtrace-mxdisplay-pyqtgraph: executable-not-elf-or-script [usr/share/mcxtrace/tools/Python/mxdisplay/pyqtgraph/mxdisplay-pyqtgraph.md]
W: mcxtrace-mxdisplay-webgl-classic: executable-not-elf-or-script [usr/share/mcxtrace/resources/doc/manuals/Python/mxdisplay/webgl-classic/mxdisplay-webgl-classic.md]
W: mcxtrace-mxdoc: executable-not-elf-or-script [usr/share/mcxtrace/resources/doc/manuals/Python/mxdoc/mxdoc.md]
W: mcxtrace-mxgui: executable-not-elf-or-script [usr/share/mcxtrace/resources/doc/manuals/Python/mxgui/mxgui.md]
W: mcxtrace-mxplot-matlab: executable-not-elf-or-script [usr/share/mcxtrace/resources/doc/manuals/matlab/mxplot/mxplot-matlab.md]
W: mcxtrace-mxplot-matlab: executable-not-elf-or-script [usr/share/mcxtrace/tools/matlab/mxplot/mcplot.m]
W: mcxtrace-mxplot-matplotlib: executable-not-elf-or-script [usr/share/mcxtrace/resources/doc/manuals/Python/mxplot/matplotlib/mxplot-matplotlib.md]
W: mcxtrace-mxplot-pyqtgraph: executable-not-elf-or-script [usr/share/mcxtrace/resources/doc/manuals/Python/mxplot/pyqtgraph/mxplot-pyqtgraph.md]
W: mcxtrace-mxplot-svg: executable-not-elf-or-script [usr/share/mcxtrace/resources/doc/manuals/Python/mxplot/svg/mxplot-svg.md]
W: mcxtrace-mxrun: executable-not-elf-or-script [usr/share/mcxtrace/resources/doc/manuals/Python/mxrun/mxrun.md]
W: mcstas: national-encoding [usr/share/mcstas/resources/share/general.c]
W: mcstas: national-encoding [usr/share/mcstas/resources/share/intersection.c]
W: mcstas: no-manual-page [usr/bin/mcstas-environment]
W: mcstas: no-manual-page [usr/bin/mcstas-postinst]
W: mcstas: no-manual-page [usr/bin/mcstas-pygen]
W: mcstas: no-manual-page [usr/bin/mcstas]
W: mcstas: no-manual-page [usr/bin/mcstas_errmsg]
W: mcstas-clusterscripts: no-manual-page [usr/bin/mcstas_mcsub_pbs]
W: mcstas-clusterscripts: no-manual-page [usr/bin/mcstas_mcsub_slurm]
W: mcstas-mcdisplay-mantid: no-manual-page [usr/bin/mcdisplay-mantid]
W: mcstas-mcdisplay-matlab: no-manual-page [usr/bin/mcdisplay-matlab]
W: mcstas-mcdisplay-matplotlib: no-manual-page [usr/bin/mcdisplay-matplotlib]
W: mcstas-mcdisplay-pyqtgraph: no-manual-page [usr/bin/mcdisplay-pyqtgraph]
W: mcstas-mcdisplay-pyqtgraph: no-manual-page [usr/bin/mcdisplay]
W: mcstas-mcdisplay-webgl: no-manual-page [usr/bin/mcdisplay-webgl]
W: mcstas-mcdisplay-webgl-classic: no-manual-page [usr/bin/mcdisplay-webgl-classic]
W: mcstas-mcdoc: no-manual-page [usr/bin/mcdoc]
W: mcstas-mcgui: no-manual-page [usr/bin/mcgui]
W: mcstas-mcplot-matlab: no-manual-page [usr/bin/mcplot-matlab]
W: mcstas-mcplot-matplotlib: no-manual-page [usr/bin/mcplot-matplotlib]
W: mcstas-mcplot-pyqtgraph: no-manual-page [usr/bin/mcplot-pyqtgraph]
W: mcstas-mcplot-pyqtgraph: no-manual-page [usr/bin/mcplot]
W: mcstas-mcplot-svg: no-manual-page [usr/bin/mcplot-svg]
W: mcstas-mcresplot: no-manual-page [usr/bin/mcresplot]
W: mcstas-mcrun: no-manual-page [usr/bin/mcrun]
W: mcstas-mcrun: no-manual-page [usr/bin/mcsplit]
W: mcstas-mcrun: no-manual-page [usr/bin/mcstas-acc_gpu_bind]
W: mcstas-mcrun: no-manual-page [usr/bin/mcstas-jupylab]
W: mcxtrace: no-manual-page [usr/bin/mcxtrace-environment]
W: mcxtrace: no-manual-page [usr/bin/mcxtrace-postinst]
W: mcxtrace: no-manual-page [usr/bin/mcxtrace-pygen]
W: mcxtrace: no-manual-page [usr/bin/mcxtrace]
W: mcxtrace: no-manual-page [usr/bin/mcxtrace_errmsg]
W: mcxtrace-clusterscripts: no-manual-page [usr/bin/mcxtrace_mcsub_pbs]
W: mcxtrace-clusterscripts: no-manual-page [usr/bin/mcxtrace_mcsub_slurm]
W: mcxtrace-mxdisplay-matlab: no-manual-page [usr/bin/mxdisplay-matlab]
W: mcxtrace-mxdisplay-matplotlib: no-manual-page [usr/bin/mxdisplay-matplotlib]
W: mcxtrace-mxdisplay-pyqtgraph: no-manual-page [usr/bin/mxdisplay-pyqtgraph]
W: mcxtrace-mxdisplay-pyqtgraph: no-manual-page [usr/bin/mxdisplay]
W: mcxtrace-mxdisplay-webgl: no-manual-page [usr/bin/mxdisplay-webgl]
W: mcxtrace-mxdisplay-webgl-classic: no-manual-page [usr/bin/mxdisplay-webgl-classic]
W: mcxtrace-mxdoc: no-manual-page [usr/bin/mxdoc]
W: mcxtrace-mxgui: no-manual-page [usr/bin/mxgui]
W: mcxtrace-mxplot-matlab: no-manual-page [usr/bin/mxplot-matlab]
W: mcxtrace-mxplot-matplotlib: no-manual-page [usr/bin/mxplot-matplotlib]
W: mcxtrace-mxplot-pyqtgraph: no-manual-page [usr/bin/mxplot-pyqtgraph]
W: mcxtrace-mxplot-pyqtgraph: no-manual-page [usr/bin/mxplot]
W: mcxtrace-mxplot-svg: no-manual-page [usr/bin/mxplot-svg]
W: mcxtrace-mxrun: no-manual-page [usr/bin/mcxtrace-acc_gpu_bind]
W: mcxtrace-mxrun: no-manual-page [usr/bin/mcxtrace-jupylab]
W: mcxtrace-mxrun: no-manual-page [usr/bin/mxrun]
W: mcxtrace-mxrun: no-manual-page [usr/bin/mxsplit]
W: mcstas-mcdisplay-mantid: package-has-long-file-name mcstas-mcdisplay-mantid_3.5+0.0~git20240719135548.728fd5e+ds5-1_amd64.deb
W: mcstas-mcdisplay-matlab: package-has-long-file-name mcstas-mcdisplay-matlab_3.5+0.0~git20240719135548.728fd5e+ds5-1_amd64.deb
W: mcstas-mcdisplay-matplotlib: package-has-long-file-name mcstas-mcdisplay-matplotlib_3.5+0.0~git20240719135548.728fd5e+ds5-1_amd64.deb
W: mcstas-mcdisplay-pyqtgraph: package-has-long-file-name mcstas-mcdisplay-pyqtgraph_3.5+0.0~git20240719135548.728fd5e+ds5-1_amd64.deb
W: mcstas-mcdisplay-webgl: package-has-long-file-name mcstas-mcdisplay-webgl_3.5+0.0~git20240719135548.728fd5e+ds5-1_amd64.deb
W: mcstas-mcdisplay-webgl-classic: package-has-long-file-name mcstas-mcdisplay-webgl-classic_3.5+0.0~git20240719135548.728fd5e+ds5-1_amd64.deb
W: mcstas-mcplot-matplotlib: package-has-long-file-name mcstas-mcplot-matplotlib_3.5+0.0~git20240719135548.728fd5e+ds5-1_amd64.deb
W: mcstas-mcplot-pyqtgraph: package-has-long-file-name mcstas-mcplot-pyqtgraph_3.5+0.0~git20240719135548.728fd5e+ds5-1_amd64.deb
W: mcxtrace-clusterscripts: package-has-long-file-name mcxtrace-clusterscripts_3.5+0.0~git20240719135548.728fd5e+ds5-1_amd64.deb
W: mcxtrace-mxdisplay-matlab: package-has-long-file-name mcxtrace-mxdisplay-matlab_3.5+0.0~git20240719135548.728fd5e+ds5-1_amd64.deb
W: mcxtrace-mxdisplay-matplotlib: package-has-long-file-name mcxtrace-mxdisplay-matplotlib_3.5+0.0~git20240719135548.728fd5e+ds5-1_amd64.deb
W: mcxtrace-mxdisplay-pyqtgraph: package-has-long-file-name mcxtrace-mxdisplay-pyqtgraph_3.5+0.0~git20240719135548.728fd5e+ds5-1_amd64.deb
W: mcxtrace-mxdisplay-webgl: package-has-long-file-name mcxtrace-mxdisplay-webgl_3.5+0.0~git20240719135548.728fd5e+ds5-1_amd64.deb
W: mcxtrace-mxdisplay-webgl-classic: package-has-long-file-name mcxtrace-mxdisplay-webgl-classic_3.5+0.0~git20240719135548.728fd5e+ds5-1_amd64.deb
W: mcxtrace-mxplot-matlab: package-has-long-file-name mcxtrace-mxplot-matlab_3.5+0.0~git20240719135548.728fd5e+ds5-1_amd64.deb
W: mcxtrace-mxplot-matplotlib: package-has-long-file-name mcxtrace-mxplot-matplotlib_3.5+0.0~git20240719135548.728fd5e+ds5-1_amd64.deb
W: mcxtrace-mxplot-pyqtgraph: package-has-long-file-name mcxtrace-mxplot-pyqtgraph_3.5+0.0~git20240719135548.728fd5e+ds5-1_amd64.deb
W: mcstas-mcgui: script-not-executable [usr/share/applications/mcstas-3.5-py.desktop]
W: mcxtrace-mxgui: script-not-executable [usr/share/applications/mcxtrace-3.5-py.desktop]
W: mcstas-comps: unusual-interpreter python [usr/share/mcstas/resources/samples/sasview_generator.py]
W: mcstas-mcgui: unusual-interpreter xdg-open [usr/share/applications/mcstas-3.5-py.desktop]
W: mcstas-mcplot-pyqtgraph: unusual-interpreter python [usr/share/mcstas/tools/Python/mcplot/pyqtgraph/mcdataclient.py]
W: mcstas-mcplot-pyqtgraph: unusual-interpreter python [usr/share/mcstas/tools/Python/mcplot/pyqtgraph/mcdataserver.py]
W: mcxtrace-mxgui: unusual-interpreter xdg-open [usr/share/applications/mcxtrace-3.5-py.desktop]
W: mcxtrace-mxplot-pyqtgraph: unusual-interpreter python [usr/share/mcxtrace/tools/Python/mxplot/pyqtgraph/mcdataclient.py]
W: mcxtrace-mxplot-pyqtgraph: unusual-interpreter python [usr/share/mcxtrace/tools/Python/mxplot/pyqtgraph/mcdataserver.py]
```

**Comment by farhi** [comment]
And we should find a way to build the component/instrument HTML files at build time, not at installation. These files do not change. I have no idea how to do that directly via CMake. You are the expert !

What can change is the overview mcdoc.html that could be stored in /tmp or locally, and may as well fetch/build local doc. I think the old perl mcdoc worked like that (mcdoc.html in /tmp).

BTW: would also be nice to clean the git repo. There are plenty of obsolete files, e.g.:
- tools/Komodo ?
- tools/Legacy-Perl* and others ?
- doc / docpkg
- INSTALL-McStas-2.x
- INSTALL-McXtrace-1.x
- mv INSTALL-McStas-3.x -> INSTALL-McStas
- mv INSTALL-McXtrace-3.x -> INSTALL-McXtrace
- generate_testplots ?
- test-batches ?
- test-utils ?
- x-test-batches ?
- install.sh (seems not to be used)

As a start, we could just move all this to `obsolete-files`.

**Pull request merged**
