### PR TITLE
Port mc/xgui go PyQt6 (seems OK for PyQt5 but needs checks->PR)

### PR DESCRIPTION
**Pull request by willend**
@farhi I have gone through the process of converting mc/xgui to use with PyQt6 - runs OK on my Debian 12.

I tested also on my mac with PyQt5 via conda, but it would be great if you could also test on various systems / setups?

### CODE REVIEW

**Comment by farhi** [comment]
Tested on McXtrace/Ubuntu 22.04 with both Qt5 and Qt6 libs.
- All works regarding plots (mxgui, mxplot, mxdisplay)

Build with meta packages fails:
```
Building metapackage
buildscripts/build_debs_mcxtrace: 73: equivs-build: not found
DEB metapackages done
WORK dir is /tmp/McCode
mv /tmp/McCode/meta-pkgs/deb/mcxtrace-suite*3.3-20240209b*.deb /tmp/McCode/dist
cp /tmp/McCode/INSTALL-McXtrace-3.x/Linux/debian/README.md /tmp/McCode/dist
mv: cannot stat '/tmp/McCode/meta-pkgs/deb/mcxtrace-suite*3.3-20240209b*.deb': No such file or directory
```

Removal of some old packages fail with:
```
(Reading database ... 689633 files and directories currently installed.)
Removing mcxtrace-3.3-20231220 (1.0) ...
find: ‘./run/user/1000/gvfs’: Permission denied
find: ‘./run/user/1000/doc’: Permission denied
basename: extra operand ‘.instr’
Try 'basename --help' for more information.
rm: cannot remove './tmp/McCode/tools/Komodo/Syntax/Components/templates': Is a directory
dpkg: error processing package mcxtrace-3.3-20231220 (--purge):
 installed mcxtrace-3.3-20231220 package post-removal script subprocess returned error exit status 1
Errors were encountered while processing:
 mcxtrace-3.3-20231220
```
I think these errors are also present in our main branch.

**Comment by willend** [comment]
@farhi thanks! 

The first one is easy, you need to install `equivs-build` on your box  to build the meta-package

Very strange with the other one, this needs attention for sure.

**Comment by farhi** [comment]
All is fine !

**Comment by willend** [comment]
Thanks again for testing. We should make this a good habit. :)

**Pull request merged**
