### PR TITLE
Implement LITERAL keyword

### PR DESCRIPTION
**Pull request by g5t**
This branch includes an implementation fulfilling my request #1470 

Unfortunately, it is on top of the current version of #1438 and includes bug fixes and other developments.
If this is acceptable, I can extract just the new-keyword related changes before merging to keep the repository history cleaner.

### CODE REVIEW

**Comment by willend** [comment]
I am trying to give this joint PR code a spin, added what I thought was the relevant syntax(es) for the two new features to the attached BNL_H8 instr

* Unit stuff seems to check out OK by itself, added like this:
`DEFINE INSTRUMENT BNL_H8 (lambda / "Aa" = 2.36)`


* I got a segfault from the code generator once I added the `LITERAL` like this:
```
COMPONENT Source = Source_simple(
  radius  = 0.10,
  dist = 2.7473,
  focus_xw = 0.031, focus_yh = 0.054,
  E0 = Ei,
  dE = 0.03*Ei)
AT (0,0,0) ABSOLUTE
LITERAL Python extra_function %{
def the_func(a,b,c):
    return a+b/c;
%}
```
Am I doing something evidently wrong?
[BNL_H8.instr.txt](https://github.com/McStasMcXtrace/McCode/files/12027753/BNL_H8.instr.txt)

**Comment by willend** [comment]
```
willend@peter:~$ $HOME/demo/mcstas/3.9999-git/environment 

The new shell started here is now set up for running this version of mcstas:

 code generator version 3.9999-git (git)
Copyright (C) DTU Physics and Risoe National Laboratory, 1997-2023
Additions (C) Institut Laue Langevin, 2003-2019
All rights reserved

Components are (C) their authors, see component headers.

To end using this version of mcstas, exit this shell.

willend@peter:~$ cd tmp/
willend@peter:~/tmp$ which mcstas
/home/willend/demo/mcstas/3.9999-git/bin/mcstas
willend@peter:~/tmp$ mcstas BNL_H8.instr
Warning: 'V_sample' is an obsolete component (not maintained).
Segmentation fault (core dumped)
willend@peter:~/tmp$ 

```
With a fresh cmake driven install process... Not getting wiser with help of `strace` at the moment either

**Comment by willend** [comment]
Same behaviour with a minimalistic example:
```
DEFINE INSTRUMENT strippeddown (lambda / "Aa" = 2.36)

TRACE

COMPONENT Origin = Arm()
AT (0,0,0) ABSOLUTE
LITERAL Python extra_function %{
def the_func(a,b,c):
    return a+b/c;
%}

END

```

**Comment by g5t** [comment]
Closing since #1477 picks up from where this left off but has `LITERAL` renamed to `METADATA` in agreement with 'standard' practice.

**Pull request closed without merging**
