### PR TITLE
[Add] UNSET macro to create special NaN

### PR DESCRIPTION
**Pull request by g5t**
- Currently there is no special value used for component parameters which are optional or mutually exclusive. Component authors may use an unphysical value in some cases, but there are examples where no suitable value exists.
- A new macro, `#define UNSET nan("0x...")`, allows components to use the special NaN value to keep track of whether a user has provided any input for the specific parameter(s). Helper functions have been added in the form of `is_unset`, `is_set`, and `is_valid`, to check whether a specific double value is the special NaN. The standard Slit.comp component has been modified to use the new NaN value, and now has logic at initialization to verify that a consistent set of parameter(s) have been provided.
- The specific NaN chosen for UNSET should not be created as the result of bad calculations elsewhere, but if it is that may lead to confusion for component authors and users. This possiblity is left for further consideration in the future.

### CODE REVIEW

**Comment by g5t** [comment]
A simple instrument to exercise some of the new parameter logic in the updated Slit component follows:
```
DEFINE INSTRUMENT test_slit()
DECLARE
%{
%}
INITIALIZE
%{
%}

TRACE

COMPONENT Origin = Progress_bar() AT (0,0,0) ABSOLUTE

COMPONENT radial_slit = Slit(radius=3.0) AT (0, 0, 1) RELATIVE PREVIOUS
COMPONENT symmetric_slit = Slit(xwidth=1.0, yheight=2.0) AT (0, 0, 1) RELATIVE PREVIOUS
COMPONENT offset_slit = Slit(xmin=1, xmax=3.0, ymin=-0.1, ymax=5.0) AT (0, 0, 1) RELATIVE PREVIOUS
COMPONENT closed_width_slit = Slit(xwidth=0.0, ymin=3.0, ymax=5.0) AT (0, 0, 1) RELATIVE PREVIOUS
COMPONENT closed_y_slit = Slit(xwidth=0.0, ymin=5.0, ymax=5.0) AT (0, 0, 1) RELATIVE PREVIOUS

FINALLY
%{
%}
END
```

**Comment by g5t** [comment]
This commit will enable the transformations required by #1249

**Comment by mads-bertelsen** [comment]
Looks good, with the new variadic functions it is much easier to read the input sanitation.

The Slit code would probably be easier to read if it handled everything related to x, then everything related to y, instead of having them intertwined.

It is a slight concern this can only work for doubles, but that is the vast majority of cases where this is relevant.

**Comment by willend** [comment]
Tried it out, looks good, pulling it.

**Pull request merged**
